"use server";
import {z} from "zod";import {revalidatePath} from "next/cache";
import {db} from "./db";import {requireUser,assertOrigin} from "./auth";import {money} from "../domain/rooms";import {pricingTypes,serviceRulesSchema,promoRulesSchema} from "../domain/booking-options";import type {Prisma} from "../../generated/prisma/client";
import type {FormState} from "../components/action-form";
async function validateScopes(tx:Prisma.TransactionClient,propertyId:string,rooms:string[],rates:string[]=[]){
 if(new Set(rooms).size!==rooms.length||new Set(rates).size!==rates.length)throw new Error("Duplicate scopes");
 if(rooms.length&&await tx.roomType.count({where:{propertyId,id:{in:rooms},deletedAt:null}})!==rooms.length)throw new Error("Invalid room scope");
 if(rates.length&&await tx.ratePlan.count({where:{propertyId,id:{in:rates}}})!==rates.length)throw new Error("Invalid rate scope");
}
const idSchema=z.union([z.literal(""),z.uuid()]);
const fail=(error:unknown):FormState=>({error:error instanceof z.ZodError?error.issues[0].message:"Changes could not be saved. Check names, dates, and values."});
export async function saveService(_:FormState,form:FormData):Promise<FormState>{const auth=await requireUser("rates.edit");try{await assertOrigin();const input=z.object({id:idSchema,name:z.string().trim().min(2).max(120),description:z.string().max(2000),price:money,pricingType:z.enum(pricingTypes),maxQuantity:z.coerce.number().int().min(1).max(20),roomTypeIds:z.array(z.uuid())}).parse({...Object.fromEntries(form),roomTypeIds:form.getAll("roomTypeIds")});const rules=serviceRulesSchema.parse({maxQuantity:input.maxQuantity,roomTypeIds:input.roomTypeIds});await db.$transaction(async tx=>{await validateScopes(tx,auth.property.id,input.roomTypeIds);const data={name:input.name,description:input.description,price:input.price,pricingType:input.pricingType,rules,active:form.has("active")};const row=input.id?await tx.service.update({where:{id:input.id,propertyId:auth.property.id},data}):await tx.service.create({data:{...data,propertyId:auth.property.id}});await tx.auditLog.create({data:{propertyId:auth.property.id,actorId:auth.user.id,action:"service.saved",entityType:"Service",entityId:row.id,after:data}});});revalidatePath("/admin/services");return{success:"Service saved."};}catch(error){return fail(error);}}
export async function savePromo(_:FormState,form:FormData):Promise<FormState>{const auth=await requireUser("rates.edit");try{await assertOrigin();const input=z.object({id:idSchema,code:z.string().trim().toUpperCase().regex(/^[A-Z0-9_-]{2,40}$/),kind:z.enum(["PERCENT","FIXED"]),value:money,startsAt:z.coerce.date(),expiresAt:z.coerce.date(),usageLimit:z.union([z.literal(""),z.coerce.number().int().min(1)]),perGuestLimit:z.coerce.number().int().min(1).max(100),minimumTotal:money,minimumNights:z.coerce.number().int().min(1).max(366),roomTypeIds:z.array(z.uuid()),ratePlanIds:z.array(z.uuid())}).refine(value=>value.expiresAt>value.startsAt,"Expiry must follow start").refine(value=>value.kind!=="PERCENT"||Number(value.value)<=100,"Percentage cannot exceed 100").parse({...Object.fromEntries(form),roomTypeIds:form.getAll("roomTypeIds"),ratePlanIds:form.getAll("ratePlanIds")});const rules=promoRulesSchema.parse({minimumTotal:String(input.minimumTotal),minimumNights:input.minimumNights,roomTypeIds:input.roomTypeIds,ratePlanIds:input.ratePlanIds,newCustomersOnly:form.has("newCustomersOnly")});await db.$transaction(async tx=>{await validateScopes(tx,auth.property.id,input.roomTypeIds,input.ratePlanIds);const data={code:input.code,kind:input.kind,value:input.value,startsAt:input.startsAt,expiresAt:input.expiresAt,usageLimit:input.usageLimit===""?null:input.usageLimit,perGuestLimit:input.perGuestLimit,rules,active:form.has("active")};const row=input.id?await tx.promoCode.update({where:{id:input.id,propertyId:auth.property.id},data}):await tx.promoCode.create({data:{...data,propertyId:auth.property.id}});await tx.auditLog.create({data:{propertyId:auth.property.id,actorId:auth.user.id,action:"promo.saved",entityType:"PromoCode",entityId:row.id,after:{...data,value:input.value}}});});revalidatePath("/admin/promotions");return{success:"Promo code saved."};}catch(error){return fail(error);}}
export async function saveTax(_:FormState,form:FormData):Promise<FormState>{const auth=await requireUser("rates.edit");try{await assertOrigin();const input=z.object({id:idSchema,name:z.string().trim().min(2).max(120),kind:z.enum(["PERCENT","FIXED"]),value:money,priority:z.coerce.number().int().min(0).max(1000)}).refine(value=>value.kind!=="PERCENT"||Number(value.value)<=100,"Percentage cannot exceed 100").parse(Object.fromEntries(form));await db.$transaction(async tx=>{const data={name:input.name,kind:input.kind,value:input.value,priority:input.priority,included:form.has("included"),active:form.has("active")};const row=input.id?await tx.taxRule.update({where:{id:input.id,propertyId:auth.property.id},data}):await tx.taxRule.create({data:{...data,propertyId:auth.property.id}});await tx.auditLog.create({data:{propertyId:auth.property.id,actorId:auth.user.id,action:"tax.saved",entityType:"TaxRule",entityId:row.id,after:{...data,value:input.value}}});});revalidatePath("/admin/taxes");return{success:"Tax or fee saved."};}catch(error){return fail(error);}}
