"use server";
import {z} from "zod";import {revalidatePath} from "next/cache";
import {db} from "./db";import {requireUser,assertOrigin} from "./auth";import {money} from "../domain/rooms";import {isoDate,stayNights} from "../domain/stay";import {rateRulesSchema} from "../domain/pricing";import type {FormState} from "../components/action-form";
const fail=(e:unknown):FormState=>({error:e instanceof z.ZodError?e.issues[0].message:e instanceof Error&&e.message.startsWith("Choose")?e.message:"Changes could not be saved. Check dates, conflicts, and required fields."});
export async function saveRate(_:FormState,form:FormData):Promise<FormState>{const auth=await requireUser("rates.edit");try{await assertOrigin();const input=z.object({name:z.string().min(2).max(100),roomTypeId:z.uuid(),basePrice:money,minStay:z.coerce.number().int().min(1).max(366),maxStay:z.coerce.number().int().min(1).max(366),policyName:z.string().min(2).max(100),freeCancellationHours:z.coerce.number().int().min(0).max(8760),cancellationPercent:z.coerce.number().min(0).max(100)}).refine(r=>r.maxStay>=r.minStay).parse(Object.fromEntries(form));
  const id=z.union([z.literal(""),z.uuid()]).parse(form.get("id")??"");
  const rules=rateRulesSchema.parse({weekendPrice:String(form.get("weekendPrice")||input.basePrice),extraAdultPrice:String(form.get("extraAdultPrice")||"0"),childPrice:String(form.get("childPrice")||"0"),includedAdults:Number(form.get("includedAdults")||2),longStayNights:Number(form.get("longStayNights")||7),longStayPercent:Number(form.get("longStayPercent")||0),earlyBookingDays:Number(form.get("earlyBookingDays")||30),earlyBookingPercent:Number(form.get("earlyBookingPercent")||0),lastMinuteDays:Number(form.get("lastMinuteDays")||2),lastMinutePercent:Number(form.get("lastMinutePercent")||0)});
  await db.$transaction(async tx=>{await tx.roomType.findFirstOrThrow({where:{id:input.roomTypeId,propertyId:auth.property.id,deletedAt:null}});if(id)await tx.ratePlan.findFirstOrThrow({where:{id,propertyId:auth.property.id}});const policy=await tx.policy.create({data:{propertyId:auth.property.id,name:input.policyName,rules:{freeCancellationHours:input.freeCancellationHours,cancellationPercent:input.cancellationPercent}}});const data={name:input.name,roomTypeId:input.roomTypeId,basePrice:input.basePrice,minStay:input.minStay,maxStay:input.maxStay,policyId:policy.id,rules,active:form.has("active")};const rate=id?await tx.ratePlan.update({where:{id},data}):await tx.ratePlan.create({data:{...data,propertyId:auth.property.id}});await tx.auditLog.create({data:{propertyId:auth.property.id,actorId:auth.user.id,action:"rate.saved",entityType:"RatePlan",entityId:rate.id,after:data}});});revalidatePath("/admin/rates");return{success:"Rate plan saved."};}catch(e){return fail(e);}}
export async function saveOverride(_:FormState,form:FormData):Promise<FormState>{const auth=await requireUser("rates.edit");try{await assertOrigin();const input=z.object({ratePlanId:z.uuid(),name:z.string().min(2).max(100),start:isoDate,end:isoDate,priority:z.coerce.number().int().min(0).max(1000),adjustment:z.enum(["REPLACE","FIXED","PERCENT"]),value:money}).refine(r=>r.end>r.start).parse(Object.fromEntries(form));
  await db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "RatePlan" WHERE id=${input.ratePlanId}::uuid FOR UPDATE`;await tx.ratePlan.findFirstOrThrow({where:{id:input.ratePlanId,propertyId:auth.property.id}});if(await tx.rateOverride.count({where:{ratePlanId:input.ratePlanId,priority:input.priority,start:{lt:new Date(input.end)},end:{gt:new Date(input.start)}}}))throw new Error("Choose a different priority; a rule with the same priority overlaps these dates.");const row=await tx.rateOverride.create({data:{...input,start:new Date(input.start),end:new Date(input.end),restrictions:{closed:form.has("closed"),noCheckIn:form.has("noCheckIn"),noCheckOut:form.has("noCheckOut")}}});await tx.auditLog.create({data:{propertyId:auth.property.id,actorId:auth.user.id,action:"override.created",entityType:"RateOverride",entityId:row.id}});});revalidatePath("/admin/rates");return{success:"Date rate added."};}catch(e){return fail(e);}}
export async function blockDates(_:FormState,form:FormData):Promise<FormState>{const auth=await requireUser("availability.edit");try{await assertOrigin();const input=z.object({unitId:z.uuid(),start:isoDate,end:isoDate,reason:z.string().min(3).max(500),kind:z.enum(["BLOCKED","MAINTENANCE"])}).parse(Object.fromEntries(form));const dates=stayNights(input.start,input.end);
  await db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "RoomUnit" WHERE id=${input.unitId}::uuid FOR UPDATE`;await tx.roomUnit.findFirstOrThrow({where:{id:input.unitId,propertyId:auth.property.id}});const block=await tx.availabilityBlock.create({data:{propertyId:auth.property.id,start:new Date(input.start),end:new Date(input.end),reason:input.reason,kind:input.kind}});await tx.inventoryNight.createMany({data:dates.map(date=>({propertyId:auth.property.id,unitId:input.unitId,date:new Date(date),blockId:block.id}))});await tx.auditLog.create({data:{propertyId:auth.property.id,actorId:auth.user.id,action:"availability.blocked",entityType:"AvailabilityBlock",entityId:block.id}});});revalidatePath("/admin/calendar");return{success:"Dates blocked."};}catch(e){return fail(e);}}
export async function releaseBlock(_:FormState,form:FormData):Promise<FormState>{const auth=await requireUser("availability.edit");try{await assertOrigin();const id=z.uuid().parse(form.get("id"));await db.$transaction(async tx=>{await tx.availabilityBlock.findFirstOrThrow({where:{id,propertyId:auth.property.id}});await tx.inventoryNight.deleteMany({where:{blockId:id,propertyId:auth.property.id}});await tx.availabilityBlock.update({where:{id},data:{releasedAt:new Date()}});await tx.auditLog.create({data:{propertyId:auth.property.id,actorId:auth.user.id,action:"availability.unblocked",entityType:"AvailabilityBlock",entityId:id}});});revalidatePath("/admin/calendar");return{success:"Block released."};}catch(e){return fail(e);}}
