import Link from "next/link";import {db} from "../../server/db";import {searchAvailability} from "../../server/availability";import {HotelShell} from "../../components/hotel-shell";import {CheckoutForm} from "../../components/checkout-form";import {CheckoutOptions} from "../../components/checkout-options";import {optionsFromSearch,serviceRulesSchema} from "../../domain/booking-options";
export const dynamic="force-dynamic";
export default async function Checkout({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const query=await searchParams,property=await db.property.findFirstOrThrow(),stay={checkIn:query.checkIn??"",checkOut:query.checkOut??"",adults:Number(query.adults??2),children:Number(query.children??0),rooms:Number(query.rooms??1)};
 let options;try{options=optionsFromSearch(query.services,query.promo);}catch{options={services:[],promoCode:""};}
 let selection:Awaited<ReturnType<typeof searchAvailability>>[number]|undefined;try{selection=(await searchAvailability(property.id,stay,db,options)).find(result=>result.rates.some(plan=>plan.id===query.ratePlanId));}catch{}const rate=selection?.rates.find(plan=>plan.id===query.ratePlanId);
 if(!selection||!rate)return <HotelShell><main id="main" className="empty-state"><h1>Let’s review your stay.</h1><p>The room, extra, or promo code selection is unavailable.</p><Link className="button" href="/rooms">Search rooms</Link></main></HotelShell>;
 const [methods,allServices]=await Promise.all([db.paymentMethod.findMany({where:{propertyId:property.id,enabled:true,provider:{in:["pay-at-hotel","cash","bank-transfer"]}}}),db.service.findMany({where:{propertyId:property.id,active:true},orderBy:{name:"asc"}})]);
 const services=allServices.flatMap(service=>{const rules=serviceRulesSchema.parse(service.rules);return rules.roomTypeIds.length&&!rules.roomTypeIds.includes(selection.room.id)?[]:[{id:service.id,name:service.name,description:service.description,price:`${property.currency} ${service.price}`,pricingType:service.pricingType,maxQuantity:rules.maxQuantity}]});const policy=rate.policy.rules as Record<string,number>;
 return <HotelShell><main id="main" className="public-container"><div className="hotel-page-heading"><span className="eyebrow">YOUR NEXT CHAPTER</span><h1>We’ll make room for you.</h1><p>Personalize your stay, review the total, and reserve.</p></div><div className="checkout-grid"><section><div className="panel padded"><CheckoutOptions services={services} promoCode={options.promoCode}/></div><div className="panel padded"><h2>Your details</h2><CheckoutForm methods={methods.map(method=>{const config=method.publicConfig as Record<string,string>;return{provider:method.provider,instructions:config.instructions??"",bankName:config.bankName??"",accountName:config.accountName??"",accountNumber:config.accountNumber??""};})} ratePlanId={rate.id} stay={stay} total={rate.quote.total} options={options}/></div></section><aside className="panel padded stay-summary"><span className="eyebrow">YOUR RESERVATION</span><h2>{selection.room.name}</h2><p>{rate.name}</p><div className="summary-dates"><span>Arrival<strong>{stay.checkIn}</strong></span><span>Departure<strong>{stay.checkOut}</strong></span></div><p>{stay.adults} adults · {stay.children} children · {stay.rooms} rooms</p><div className="price-lines">{rate.quote.nightly.map(night=><div key={night.date}><span>{night.date}</span><span>{property.currency} {night.amount}</span></div>)}{rate.quote.extras.map(extra=><div key={extra.name}><span>{extra.name} × {extra.quantity}</span><span>{property.currency} {extra.total}</span></div>)}{rate.quote.discount!=="0.00"?<div><span>Promo {rate.promo?.code}</span><span>− {property.currency} {rate.quote.discount}</span></div>:null}{rate.quote.taxes.map(tax=><div key={tax.name}><span>{tax.name}{tax.included?" (included)":""}</span><span>{property.currency} {tax.amount}</span></div>)}<div className="total"><strong>Total</strong><strong>{property.currency} {rate.quote.total}</strong></div></div><h3>{rate.policy.name}</h3><p className="muted">Free cancellation until {policy.freeCancellationHours??0} hours before arrival. Later cancellations incur a {policy.cancellationPercent??100}% fee.</p></aside></div></main></HotelShell>;
}
