import {z} from "zod";
export const safeUrl=z.string().trim().max(2000).refine(value=>value===""||value==="#"||(/^\/(?![\\/])/.test(value)&&!/[\x00-\x20\\]/.test(value))||(/^https:\/\//.test(value)&&(()=>{try{const u=new URL(value);return!u.username&&!u.password;}catch{return false;}})()),"Use an internal path or a secure https:// URL");
export const imageId=z.union([z.literal(""),z.uuid()]).default("");
export const sectionTypes=["hero","text","image-text","rooms","amenities","gallery","offers","testimonials","faq","stats","cta","contact","video","cards","newsletter"] as const;
export const sectionSchema=z.object({
 id:z.uuid(),type:z.enum(sectionTypes),visible:z.boolean().default(true),startsAt:z.string().datetime().nullable().default(null),endsAt:z.string().datetime().nullable().default(null),
 content:z.object({eyebrow:z.string().max(150).default(""),heading:z.string().max(300).default(""),body:z.string().max(20000).default(""),imageId,ctaLabel:z.string().max(100).default(""),ctaUrl:safeUrl.default(""),videoUrl:safeUrl.default(""),items:z.array(z.object({title:z.string().max(200),body:z.string().max(2000).default(""),imageId,url:safeUrl.default("")})).max(30).default([])}).strict(),
 style:z.object({background:z.enum(["white","mist","ink"]).default("white"),align:z.enum(["left","center"]).default("left"),spacing:z.enum(["compact","normal","spacious"]).default("normal"),width:z.enum(["contained","full"]).default("contained")}).strict(),
}).strict().refine(s=>!s.startsAt||!s.endsAt||s.endsAt>s.startsAt,"Visibility end must follow start");
export type PageSectionInput=z.infer<typeof sectionSchema>;
export const pageDocumentSchema=z.object({title:z.string().trim().min(2).max(200),slug:z.string().regex(/^(?:home|[a-z0-9]+(?:-[a-z0-9]+)*)$/).max(100),locale:z.enum(["en","bn","ar","hi"]).default("en"),seoTitle:z.string().max(200).default(""),description:z.string().max(500).default(""),noIndex:z.boolean().default(false),sections:z.array(sectionSchema).max(50)}).strict().refine(p=>new Set(p.sections.map(s=>s.id)).size===p.sections.length,"Section IDs must be unique");
export type PageDocument=z.infer<typeof pageDocumentSchema>;
export const reservedSlugs=new Set(["admin","api","login","setup","checkout","confirmation","media","rooms","collections","forms","preview","sitemap","robots","forgot-password","reset-password"]);
export function sectionVisible(section:PageSectionInput,now=new Date()){return section.visible&&(!section.startsAt||new Date(section.startsAt)<=now)&&(!section.endsAt||new Date(section.endsAt)>now);}
export function blankSection(type:typeof sectionTypes[number],id:string):PageSectionInput{return sectionSchema.parse({id,type,visible:true,content:{},style:{}});}

export type SettingField={key:string;label:string;type:"text"|"textarea"|"color"|"number"|"checkbox"|"select"|"image"|"url";default:string|number|boolean;options?:string[];min?:number;max?:number};
type SettingsModule={title:string;description:string;permission:"website.edit"|"settings.manage"|"website.scripts";fields:SettingField[]};
const color=(key:string,label:string,value:string):SettingField=>({key,label,type:"color",default:value});
const text=(key:string,label:string,value=""):SettingField=>({key,label,type:"text",default:value});
const bool=(key:string,label:string,value=false):SettingField=>({key,label,type:"checkbox",default:value});
const number=(key:string,label:string,value:number,min=0,max=2000):SettingField=>({key,label,type:"number",default:value,min,max});
export const settingsModules:Record<string,SettingsModule>={
 theme:{title:"Appearance",description:"Brand colors, typography, and the shape of your website.",permission:"website.edit",fields:[
  {key:"logoId",label:"Brand logo",type:"image",default:""},{key:"faviconId",label:"Browser icon",type:"image",default:""},text("tagline","Tagline"),
  color("primary","Primary color","#21656c"),color("secondary","Secondary color","#173c43"),color("accent","Accent color","#a88045"),color("background","Page background","#ffffff"),color("secondaryBackground","Section background","#e5efed"),color("text","Body text","#173c43"),color("muted","Secondary text","#697b7d"),color("heading","Headings","#173c43"),color("button","Button background","#21656c"),color("buttonText","Button text","#ffffff"),color("link","Links","#21656c"),color("success","Success","#286249"),color("warning","Warning","#8a691c"),color("error","Error","#953b2a"),
  ...["headingFont","bodyFont","navigationFont","buttonFont"].map(key=>({key,label:key.replace("Font"," font"),type:"select" as const,default:key==="headingFont"?"Libre Caslon Display":"DM Sans",options:["Libre Caslon Display","DM Sans","Georgia","Arial","Verdana"]})),
  number("contentWidth","Content width (px)",1240,800,1800),number("bodySize","Body text size (px)",14,12,22),number("headingSize","Page heading size (px)",64,28,110),number("radius","Corner radius (px)",8,0,40),number("sectionSpacing","Section spacing (px)",70,20,160),number("lineHeight","Body line height (%)",170,120,220),
 ]},
 header:{title:"Header",description:"Brand presentation and the main booking button.",permission:"website.edit",fields:[bool("sticky","Keep header visible while scrolling",true),bool("transparent","Transparent header"),color("background","Background","#ffffff"),color("text","Text color","#173c43"),number("height","Header height (px)",90,60,160),number("logoWidth","Logo width (px)",130,60,300),text("buttonLabel","Booking button label","Find a room"),{key:"buttonUrl",label:"Booking button link",type:"url",default:"/rooms"},bool("showPhone","Show hotel telephone"),bool("showEmail","Show hotel email")]},
 footer:{title:"Footer",description:"Footer copy, colors, and links.",permission:"website.edit",fields:[{key:"description",label:"Footer description",type:"textarea",default:""},text("contactHeading","Contact heading","Stay in touch"),text("arrivalHeading","Arrival heading","Your arrival"),text("copyright","Copyright text"),color("background","Background","#173c43"),color("text","Text color","#d8e6e2"),{key:"instagram",label:"Instagram URL",type:"url",default:""},{key:"facebook",label:"Facebook URL",type:"url",default:""},{key:"youtube",label:"YouTube URL",type:"url",default:""},bool("newsletter","Show newsletter signup")]},
 seo:{title:"Search & sharing",description:"Search titles, descriptions, and social sharing defaults.",permission:"website.edit",fields:[text("title","Default website title"),{key:"description",label:"Default description",type:"textarea",default:""},text("keywords","Keywords"),{key:"ogImageId",label:"Social sharing image",type:"image",default:""},bool("noIndex","Hide website from search engines")]},
 booking:{title:"Booking rules",description:"Set the guest counts, stay lengths, and booking window your hotel accepts.",permission:"settings.manage",fields:[bool("enabled","Enable public bookings",true),number("maxRooms","Maximum rooms per reservation",5,1,20),number("maxAdults","Maximum adults",20,1,100),number("maxChildren","Maximum children",10,0,100),number("minStay","Minimum nights",1,1,365),number("advanceDays","Maximum advance booking (days)",365,1,730),number("noticeDays","Minimum booking notice (days)",0,0,365),bool("sameDay","Allow same-day bookings",true),number("cutoffHour","Same-day booking cutoff hour",18,0,23)]},
 features:{title:"Website features",description:"Choose which optional parts of your website appear.",permission:"website.edit",fields:[...(["offers","testimonials","gallery","faq","newsletter","blog","restaurant","spa","events"] as const).map(key=>bool(key,`Show ${key}`,true)),bool("showPrices","Show prices on room listings",true),bool("showInventory","Show available room counts",true)]},
 announcement:{title:"Announcement bar",description:"A scheduled message at the top of your website.",permission:"website.edit",fields:[bool("enabled","Enable announcement"),text("message","Announcement message"),{key:"url",label:"Link",type:"url",default:""},text("startsAt","Start (ISO date and time)"),text("endsAt","End (ISO date and time)"),color("background","Background","#173c43"),color("text","Text","#ffffff"),bool("dismissible","Allow guests to dismiss",true)]},
 maintenance:{title:"Maintenance mode",description:"Show a temporary message while your website is being prepared. Admin remains accessible.",permission:"settings.manage",fields:[bool("enabled","Enable maintenance mode"),text("title","Heading","We’re preparing your next stay."),{key:"message",label:"Message",type:"textarea",default:"Please contact the hotel for reservations."},text("reopening","Expected reopening"),{key:"imageId",label:"Image",type:"image",default:""}]},
 cookies:{title:"Cookie preferences",description:"Allow guests to control optional tracking.",permission:"website.edit",fields:[bool("enabled","Show cookie consent",true),{key:"message",label:"Consent message",type:"textarea",default:"We use essential cookies to keep reservations and sign-in secure. Optional analytics are used only with your consent."},{key:"policyUrl",label:"Privacy policy link",type:"url",default:"/privacy-policy"},text("acceptLabel","Accept button","Accept optional cookies"),text("rejectLabel","Reject button","Essential only")]},
 popup:{title:"Promotional popup",description:"A dismissible, scheduled promotion for website visitors.",permission:"website.edit",fields:[bool("enabled","Enable popup"),text("title","Title"),{key:"body",label:"Message",type:"textarea",default:""},{key:"imageId",label:"Image",type:"image",default:""},text("buttonLabel","Button label","Explore offer"),{key:"buttonUrl",label:"Button link",type:"url",default:"/offers"},number("delaySeconds","Delay before showing (seconds)",10,1,120),number("frequencyDays","Days between displays",7,1,90),text("startsAt","Start (ISO date and time)"),text("endsAt","End (ISO date and time)")]},
 invoice:{title:"Invoices",description:"Invoice numbering and printed hotel information.",permission:"settings.manage",fields:[text("prefix","Invoice prefix","INV"),{key:"footer",label:"Invoice footer",type:"textarea",default:"Thank you for choosing to stay with us."},{key:"taxInformation",label:"Tax registration information",type:"textarea",default:""}]},
 tracking:{title:"Analytics integration",description:"Consent-controlled analytics. Available only to Super Admin.",permission:"website.scripts",fields:[text("googleAnalyticsId","Google Analytics measurement ID"),bool("enabled","Enable analytics after consent")]},
};
export function settingsSchema(namespace:string){const definition=settingsModules[namespace];if(!definition)throw new Error("Unknown settings area");return z.object(Object.fromEntries(definition.fields.map(field=>{
 let schema:z.ZodType=field.type==="checkbox"?z.boolean():field.type==="number"?z.number().min(field.min??0).max(field.max??2000):field.type==="color"?z.string().regex(/^#[0-9a-fA-F]{6}$/):field.type==="image"?imageId:field.type==="url"?safeUrl:field.type==="select"?z.string().refine(v=>field.options?.includes(v)??false):z.string().max(field.type==="textarea"?10000:1000);
 if(field.key==="googleAnalyticsId")schema=z.string().regex(/^(?:G-[A-Z0-9]{4,20})?$/);
 if(field.key==="startsAt"||field.key==="endsAt")schema=z.union([z.literal(""),z.string().datetime()]);
 if(field.key==="prefix")schema=z.string().regex(/^[A-Z0-9-]{1,20}$/);
 return [field.key,schema.default(field.default)];
}))).strict();}
