import {z} from "zod";
const internalPath=z.string().trim().max(2000).refine(value=>/^\/(?![/\\\s])[^\\\x00-\x20]*$/.test(value),"URL must start with / and contain no spaces.");
const externalUrl=z.string().trim().max(2000).refine(value=>{try{const url=new URL(value);return (url.protocol==="http:"||url.protocol==="https:")&&!url.username&&!url.password;}catch{return false;}},"URL must start with http:// or https://.");
const nullableUuid=z.uuid().nullable().default(null);
const itemSchema=z.object({id:z.uuid(),label:z.string().trim().min(1,"Label cannot be empty.").max(100),url:z.string().trim().max(2000).default(""),linkType:z.enum(["internal","external","page"]).default("internal"),pageId:nullableUuid,externalUrl:z.string().trim().max(2000).nullable().default(null),parentId:nullableUuid,visible:z.boolean(),newTab:z.boolean(),order:z.number().int().nonnegative().optional()}).superRefine((item,ctx)=>{
 if(item.linkType==="internal"){if(item.pageId||item.externalUrl)ctx.addIssue({code:"custom",path:["url"],message:"Internal links cannot have a page or external URL."});else{const result=internalPath.safeParse(item.url);if(!result.success)ctx.addIssue({code:"custom",path:["url"],message:result.error.issues[0].message});}}
 if(item.linkType==="external"){const result=externalUrl.safeParse(item.externalUrl??item.url);if(!result.success)ctx.addIssue({code:"custom",path:["url"],message:result.error.issues[0].message});}
 if(item.linkType==="page"&&!item.pageId)ctx.addIssue({code:"custom",path:["pageId"],message:"Target page is required."});
 if(item.linkType!=="page"&&item.pageId)ctx.addIssue({code:"custom",path:["pageId"],message:"Only page links may reference a CMS page."});
});
export const navigationSchema=z.object({name:z.enum(["header","footer"]),items:z.array(itemSchema).max(60)}).superRefine((menu,ctx)=>{const ids=new Set(menu.items.map(i=>i.id));if(ids.size!==menu.items.length)ctx.addIssue({code:"custom",path:["items"],message:"Menu item IDs must be unique."});const byId=new Map(menu.items.map(item=>[item.id,item]));for(const [index,item] of menu.items.entries()){if(item.parentId===item.id)ctx.addIssue({code:"custom",path:["items",index,"parentId"],message:`${item.label} cannot be its own parent.`});if(item.parentId&&!ids.has(item.parentId))ctx.addIssue({code:"custom",path:["items",index,"parentId"],message:`${item.label}: parent item is missing.`});const visited=new Set<string>();let parentId=item.parentId;while(parentId){if(visited.has(parentId)){ctx.addIssue({code:"custom",path:["items",index,"parentId"],message:`${item.label}: parent relationships contain a cycle.`});break;}visited.add(parentId);if(visited.size>3){ctx.addIssue({code:"custom",path:["items",index,"parentId"],message:"Menus support at most four levels."});break;}parentId=byId.get(parentId)?.parentId??null;}}});
export type NavigationInput=z.infer<typeof navigationSchema>;
