import { db } from "../../../server/db";
import { requireUser } from "../../../server/auth";
import { ActionForm } from "../../../components/action-form";
import { saveUnit } from "../../../server/room-actions";
export default async function Units({ searchParams }: { searchParams: Promise<{ edit?: string }> }) {
  const { property } = await requireUser("rooms.edit"); const { edit } = await searchParams;
  const [units, rooms] = await Promise.all([db.roomUnit.findMany({ where:{propertyId:property.id}, include:{roomType:true},orderBy:{number:"asc"},take:200}),db.roomType.findMany({where:{propertyId:property.id,deletedAt:null},orderBy:{name:"asc"}})]);
  const selected=units.find(u=>u.id===edit);
  return <><div className="page-heading"><div><span className="eyebrow">PHYSICAL INVENTORY</span><h1>Every room, accounted for.</h1><p className="muted">Manage room numbers and housekeeping status.</p></div></div><div className="split-layout"><section className="panel"><div className="panel-heading"><h2>Room units</h2><span>{units.length} rooms</span></div><div className="table-scroll"><table><thead><tr><th>Number</th><th>Type</th><th>Status</th><th /></tr></thead><tbody>{units.map(u=><tr key={u.id}><td><strong>{u.number}</strong></td><td>{u.roomType.name}</td><td><span className="badge">{u.housekeeping.toLowerCase().replaceAll("_"," ")}</span><small>{u.status.toLowerCase().replaceAll("_"," ")}</small></td><td><a href={`?edit=${u.id}`}>Edit</a></td></tr>)}</tbody></table></div>{!units.length&&<div className="empty-state"><h3>No physical rooms yet.</h3><p>Add room numbers to create bookable inventory.</p></div>}</section><section className="panel padded"><h2>{selected?`Edit room ${selected.number}`:"Add a physical room"}</h2>{rooms.length ? <ActionForm key={selected?.id??"new"} action={saveUnit} label="Save physical room"><input type="hidden" name="id" value={selected?.id??""}/><label>Room number<input name="number" defaultValue={selected?.number} required/></label><label>Room type<select name="roomTypeId" defaultValue={selected?.roomTypeId}>{rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Availability status<select name="status" defaultValue={selected?.status}>{["ACTIVE","OUT_OF_SERVICE","RETIRED"].map(s=><option key={s}>{s}</option>)}</select></label><label>Housekeeping<select name="housekeeping" defaultValue={selected?.housekeeping}>{["CLEAN","DIRTY","CLEANING","INSPECTED","MAINTENANCE"].map(s=><option key={s}>{s}</option>)}</select></label><label>Internal note<textarea name="note" defaultValue={selected?.note??""}/></label></ActionForm>:<p className="muted">Create a room type first.</p>}</section></div></>;
}
