import {db} from "../../../server/db";
import {requireUser} from "../../../server/auth";
import {ActionForm} from "../../../components/action-form";
import {Field} from "../../../components/fields";
import {saveRate,saveOverride} from "../../../server/rate-actions";
export default async function Rates({searchParams}:{searchParams:Promise<{edit?:string}>}){
 const {property}=await requireUser("rates.edit");const {edit}=await searchParams;
 const [rooms,rates]=await Promise.all([db.roomType.findMany({where:{propertyId:property.id,deletedAt:null},orderBy:{name:"asc"}}),db.ratePlan.findMany({where:{propertyId:property.id},include:{roomType:true,policy:true,overrides:true},orderBy:{name:"asc"}})]);
 const selected=rates.find(r=>r.id===edit),rules=(selected?.rules??{}) as Record<string,string|number>,policy=(selected?.policy.rules??{}) as Record<string,number>;
 return <><div className="page-heading"><div><span className="eyebrow">RATES & PRICING</span><h1>The right rate. Every night.</h1><p className="muted">Flexible plans, seasonal rates, and clear cancellation terms.</p></div></div>
 <section className="panel"><div className="panel-heading"><h2>Rate plans</h2><span>{rates.length} plans</span></div><div className="table-scroll"><table><thead><tr><th>Plan</th><th>Room</th><th>Nightly price</th><th>Stay</th><th>Status</th><th/></tr></thead><tbody>{rates.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.policy.name}</small></td><td>{r.roomType.name}</td><td>{property.currency} {r.basePrice.toString()}</td><td>{r.minStay}–{r.maxStay} nights</td><td><span className="badge">{r.active?"Active":"Disabled"}</span></td><td><a href={`?edit=${r.id}`}>Edit</a></td></tr>)}</tbody></table></div>{!rates.length&&<div className="empty-state"><h3>Create your first rate plan.</h3><p>A published room needs an active rate plan before guests can book it.</p></div>}</section>
 <div className="split-layout"><section className="panel padded"><h2>{selected?`Edit ${selected.name}`:"Create a rate plan"}</h2>{rooms.length?<ActionForm key={selected?.id??"new"} action={saveRate} label="Save rate plan"><input type="hidden" name="id" value={selected?.id??""}/><div className="form-grid"><Field name="name" label="Plan name" value={selected?.name} required/><label>Room type<select name="roomTypeId" defaultValue={selected?.roomTypeId}>{rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><Field name="basePrice" label="Base nightly price" type="number" min={0} step="0.01" value={selected?.basePrice.toString()??"0"} required/><Field name="weekendPrice" label="Weekend price" type="number" min={0} step="0.01" value={rules.weekendPrice}/><Field name="minStay" label="Minimum nights" type="number" min={1} max={366} value={selected?.minStay??1} required/><Field name="maxStay" label="Maximum nights" type="number" min={1} max={366} value={selected?.maxStay??30} required/></div><details><summary>Guest charges and stay discounts</summary><div className="form-grid">{([ ["includedAdults","Included adults",2],["extraAdultPrice","Extra adult per night",0],["childPrice","Child per night",0],["longStayNights","Long stay threshold (nights)",7],["longStayPercent","Long stay discount (%)",0],["earlyBookingDays","Early booking threshold (days)",30],["earlyBookingPercent","Early booking discount (%)",0],["lastMinuteDays","Last-minute threshold (days)",2],["lastMinutePercent","Last-minute discount (%)",0] ] as const).map(([name,label,value])=><Field key={name} name={name} label={label} type="number" min={0} step="0.01" value={rules[name]??value}/>)}</div></details><fieldset><legend>Cancellation policy</legend><Field name="policyName" label="Policy name" value={selected?.policy.name??"Flexible cancellation"} required/><div className="form-grid"><Field name="freeCancellationHours" label="Free cancellation before arrival (hours)" type="number" min={0} value={policy.freeCancellationHours??48}/><Field name="cancellationPercent" label="Late cancellation fee (%)" type="number" min={0} max={100} value={policy.cancellationPercent??100}/></div></fieldset><label className="checkbox"><input type="checkbox" name="active" defaultChecked={selected?.active??true}/>Available for bookings</label></ActionForm>:<p className="muted">Create a room type first.</p>}</section>
 <section className="panel padded"><h2>Add a date-specific rate</h2>{rates.length?<ActionForm action={saveOverride} label="Add date rate"><label>Rate plan<select name="ratePlanId">{rates.map(r=><option key={r.id} value={r.id}>{r.name} · {r.roomType.name}</option>)}</select></label><Field name="name" label="Season or event name" required/><div className="form-grid"><Field name="start" label="From" type="date" required/><Field name="end" label="Until (excluded)" type="date" required/></div><label>Adjustment<select name="adjustment"><option value="REPLACE">Set nightly price</option><option value="FIXED">Add fixed amount</option><option value="PERCENT">Increase by percentage</option></select></label><div className="form-grid"><Field name="value" label="Amount" type="number" min={0} step="0.01" required/><Field name="priority" label="Priority (highest wins)" type="number" min={0} max={1000} value={10} required/></div>{[["closed","Closed for stays"],["noCheckIn","No arrivals"],["noCheckOut","No departures"]].map(([name,label])=><label key={name} className="checkbox"><input type="checkbox" name={name}/>{label}</label>)}</ActionForm>:<p className="muted">Create a rate plan first.</p>}</section></div>
 <section className="panel"><div className="panel-heading"><h2>Seasonal and date rates</h2></div>{rates.flatMap(r=>r.overrides.map(o=><div className="list-row" key={o.id}><span><strong>{o.name}</strong><small>{r.name} · {o.start.toISOString().slice(0,10)} to {o.end.toISOString().slice(0,10)}</small></span><span>{o.adjustment} {o.value.toString()} · Priority {o.priority}</span></div>))}{!rates.some(r=>r.overrides.length)&&<div className="empty-state"><p>No date rates yet. Base and weekend rates apply.</p></div>}</section></>;
}
