import Link from "next/link";
import {db} from "../../../server/db";
import {requireUser} from "../../../server/auth";

export default async function Guests({searchParams}:{searchParams:Promise<{q?:string;filter?:string;page?:string}>}){
 const {property}=await requireUser("guest.view");const query=await searchParams;const search=(query.q??"").trim().slice(0,150);const page=Math.max(1,Math.min(10000,Math.floor(Number(query.page)||1)));
 const where={propertyId:property.id,deletedAt:null,...(query.filter==="vip"?{vip:true}:query.filter==="blocked"?{blacklisted:true}:{}),...(search?{OR:[{name:{contains:search,mode:"insensitive" as const}},{email:{contains:search,mode:"insensitive" as const}},{phone:{contains:search}}]}:{})};
 const [guests,total]=await Promise.all([db.guest.findMany({where,orderBy:[{vip:"desc"},{name:"asc"},{id:"asc"}],skip:(page-1)*25,take:25,include:{_count:{select:{bookings:true}}}}),db.guest.count({where})]);
 const link=(value:number)=>`?${new URLSearchParams({q:search,filter:query.filter??"",page:String(value)})}`;
 return <><div className="page-heading"><div><span className="eyebrow">GUEST RELATIONSHIPS</span><h1>Remember every welcome.</h1><p className="muted">{total} guest profiles · contact details, preferences, and stay history.</p></div></div><form className="toolbar"><label>Search guests<input name="q" defaultValue={search} placeholder="Name, email, or phone"/></label><label>Show<select name="filter" defaultValue={query.filter??""}><option value="">All guests</option><option value="vip">VIP guests</option><option value="blocked">Booking blocked</option></select></label><button className="button secondary">Search</button></form><section className="panel">{guests.map(guest=><Link className="list-row" key={guest.id} href={`/admin/guests/${guest.id}`}><span><strong>{guest.name}</strong><small>{guest.email} {guest.phone?`· ${guest.phone}`:""}</small></span><span>{guest.vip&&<span className="badge green">VIP</span>} {guest.blacklisted&&<span className="badge">Booking blocked</span>}<small>{guest._count.bookings} reservations</small></span></Link>)}{!guests.length&&<div className="empty-state"><h2>No matching guests.</h2><p>Guest profiles are created when reservations are made.</p></div>}</section><nav className="toolbar" aria-label="Guest pages">{page>1&&<Link href={link(page-1)}>Previous</Link>}{page*25<total&&<Link href={link(page+1)}>Next</Link>}</nav></>;
}
