import Link from "next/link";
import {db} from "../../../server/db";
import {requireUser} from "../../../server/auth";
import {permissions} from "../../../domain/permissions";
import {saveRoleAction,deleteRoleAction} from "../../../server/staff-actions";
import {ActionForm} from "../../../components/action-form";

export default async function Roles({searchParams}:{searchParams:Promise<{edit?:string}>}){
 const {property,principal}=await requireUser("roles.manage");const {edit}=await searchParams;
 const roles=await db.role.findMany({where:{OR:[{system:true},{propertyId:property.id}]},include:{permissions:true,_count:{select:{memberships:{where:{propertyId:property.id}}}}},orderBy:[{system:"desc"},{name:"asc"}]});
 const selected=roles.find(role=>role.id===edit);const groups=[...new Set(permissions.map(permission=>permission.split(".")[0]))];
 return <><div className="page-heading"><div><span className="eyebrow">STAFF ACCESS</span><h1>A role for every responsibility.</h1><p className="muted">Create hotel-specific roles with only the permissions each job needs.</p></div><Link className="button secondary" href="/admin/roles">New role</Link></div><div className="split-layout"><section className="panel"><div className="panel-heading"><h2>Available roles</h2><Link href="/admin/staff">Staff accounts ↗</Link></div>{roles.map(role=><Link className="list-row" key={role.id} href={`?edit=${role.id}`}><span><strong>{role.name}</strong><small>{role.permissions.length} permissions · {role._count.memberships} staff</small></span><span className="badge">{role.system?"System":"Custom"}</span></Link>)}</section><section className="panel padded"><h2>{selected?.name??"Create role"}</h2>{selected?.system?<><p className="muted">System roles are fixed. Create a custom role to choose different permissions.</p><ul>{selected.permissions.map(grant=><li key={grant.permissionKey}>{grant.permissionKey}</li>)}</ul></>:<ActionForm key={`${selected?.id??"new"}:${selected?.version??0}`} action={saveRoleAction} label="Save role"><input type="hidden" name="id" value={selected?.id??""}/><input type="hidden" name="version" value={selected?.version??0}/><label>Role name<input name="name" required minLength={2} maxLength={80} defaultValue={selected?.name??""}/></label>{groups.map(group=><fieldset className="permission-group" key={group}><legend>{group}</legend>{permissions.filter(permission=>permission.startsWith(`${group}.`)&&principal.permissions.includes(permission)).map(permission=><label className="checkbox" key={permission}><input name="permissions" type="checkbox" value={permission} defaultChecked={selected?.permissions.some(grant=>grant.permissionKey===permission)??false}/>{permission}</label>)}</fieldset>)}<p className="muted">Saving changes signs out staff assigned to this role. You cannot edit your own assigned role.</p></ActionForm>}{selected&&!selected.system&&<details><summary>Delete custom role</summary><ActionForm action={deleteRoleAction} label="Delete role"><input type="hidden" name="id" value={selected.id}/><input type="hidden" name="version" value={selected.version}/><label>Type DELETE to confirm<input name="confirmation" required pattern="DELETE"/></label><p className="muted">Roles assigned to staff cannot be deleted.</p></ActionForm></details>}</section></div></>;
}
