import { db } from "../../../server/db";
import { requireUser } from "../../../server/auth";
import { ActionForm } from "../../../components/action-form";
import { saveAmenity } from "../../../server/room-actions";
export default async function Amenities({searchParams}:{searchParams:Promise<{edit?:string}>}) {
  const {property}=await requireUser("rooms.edit");const {edit}=await searchParams;
  const rows=await db.amenity.findMany({where:{propertyId:property.id},orderBy:{name:"asc"}});const selected=rows.find(r=>r.id===edit);
  return <><div className="page-heading"><div><span className="eyebrow">THE LITTLE COMFORTS</span><h1>Amenities.</h1><p className="muted">Create and manage the features that make a stay special.</p></div></div><div className="split-layout"><section className="panel"><div className="panel-heading"><h2>Your amenities</h2><span>{rows.length} amenities</span></div>{rows.map(r=><a key={r.id} className="list-row" href={`?edit=${r.id}`}><span><strong>{r.name}</strong><small>{r.description}</small></span><span className={`badge ${r.active?"green":""}`}>{r.active?"Active":"Hidden"}</span></a>)}{!rows.length&&<div className="empty-state"><h3>No amenities created yet.</h3><p>Add your first amenity using the form.</p></div>}</section><section className="panel padded"><h2>{selected?"Edit amenity":"Add an amenity"}</h2><ActionForm key={selected?.id??"new"} action={saveAmenity} label="Save amenity"><input type="hidden" name="id" value={selected?.id??""}/><label>Name<input name="name" defaultValue={selected?.name} required/></label><label>Category<input name="category" defaultValue={selected?.category??""}/></label><label>Description<textarea name="description" defaultValue={selected?.description??""}/></label><label>Icon<select name="icon" defaultValue={selected?.icon??"check"}>{["wifi","coffee","waves","car","wind","tv","check"].map(i=><option key={i}>{i}</option>)}</select></label><label className="checkbox"><input type="checkbox" name="active" defaultChecked={selected?.active??true}/>Active</label></ActionForm></section></div></>;
}
