import Link from "next/link";
import {z} from "zod";
import {db} from "../../../server/db";
import {requireUser} from "../../../server/auth";
import {staffFingerprint} from "../../../server/staff";
import {saveStaffAction} from "../../../server/staff-actions";
import {ActionForm} from "../../../components/action-form";

export default async function Staff({searchParams}:{searchParams:Promise<{edit?:string}>}){
 const {property,principal}=await requireUser("users.manage");const {edit}=await searchParams;
 const [members,roles]=await Promise.all([db.membership.findMany({where:{propertyId:property.id},include:{user:{select:{id:true,name:true,email:true,disabledAt:true,passwordHash:true}},role:true},orderBy:{user:{name:"asc"}}}),db.role.findMany({where:{OR:[{system:true},{propertyId:property.id}]},include:{permissions:true},orderBy:{name:"asc"}})]);
 const selected=z.uuid().safeParse(edit).success?members.find(member=>member.userId===edit):undefined;
 const assignable=roles.filter(role=>role.permissions.every(grant=>principal.permissions.some(permission=>permission===grant.permissionKey)));
 const fingerprint=selected?staffFingerprint(selected.user,selected.roleId):"";
 return <><div className="page-heading"><div><span className="eyebrow">YOUR PROPERTY TEAM</span><h1>The people behind the welcome.</h1><p className="muted">Create staff accounts and manage their access.</p></div><Link className="button secondary" href="/admin/staff">New staff account</Link></div><div className="split-layout"><section className="panel"><div className="panel-heading"><h2>Staff accounts</h2>{principal.permissions.includes("roles.manage")&&<Link href="/admin/roles">Manage roles ↗</Link>}</div>{members.map(member=><Link className="list-row" href={`?edit=${member.userId}`} key={member.userId}><span><strong>{member.user.name}</strong><small>{member.user.email} · {member.role.name}</small></span><span className={`badge ${member.user.disabledAt?"":"green"}`}>{member.user.disabledAt?"Disabled":"Active"}</span></Link>)}</section><section className="panel padded"><h2>{selected?"Edit staff account":"Create staff account"}</h2><ActionForm key={`${selected?.userId??"new"}:${fingerprint}`} action={saveStaffAction} label={selected?"Save staff account":"Create staff account"}><input type="hidden" name="id" value={selected?.userId??""}/><input type="hidden" name="fingerprint" value={fingerprint}/><label>Name<input name="name" required maxLength={100} defaultValue={selected?.user.name??""}/></label><label>Email<input name="email" type="email" required maxLength={254} autoComplete="off" defaultValue={selected?.user.email??""}/></label><label>Role<select name="roleId" required defaultValue={selected?.roleId??""}><option value="">Choose a role</option>{assignable.map(role=><option value={role.id} key={role.id}>{role.name}</option>)}</select></label><label>{selected?"New password (leave blank to keep current password)":"Initial password"}<input name="password" type="password" minLength={12} maxLength={128} required={!selected} autoComplete="new-password"/></label><label className="checkbox"><input name="disabled" type="checkbox" defaultChecked={!!selected?.user.disabledAt}/>Disable sign-in</label>{selected&&<label>Type CONFIRM when changing access or password<input name="confirmation" autoComplete="off"/></label>}<p className="muted">Role changes, password resets, and disabling access sign the staff member out. Share initial credentials through your usual secure channel.</p></ActionForm></section></div></>;
}
