import Link from "next/link";
import {reportPeriodSchema} from "../../../domain/reports";
import {requireUser} from "../../../server/auth";
import {propertyReport} from "../../../server/reports";

export default async function Reports({searchParams}:{searchParams:Promise<{from?:string;to?:string}>}){
 const {property,principal}=await requireUser("reports.view"),query=await searchParams;
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:property.timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
 const input={from:query.from??`${today.slice(0,8)}01`,to:query.to??today},parsed=reportPeriodSchema.safeParse(input),report=parsed.success?await propertyReport(principal,parsed.data):null;
 const maxRevenue=report?Math.max(1,...report.days.map(day=>Number(day.roomRevenue))):1;
 return <>
  <div className="page-heading"><div><span className="eyebrow">PROPERTY PERFORMANCE</span><h1>Know where you stand.</h1><p className="muted">Room performance, bookings, payments, refunds, and acquisition by local hotel date.</p></div>{report?<div className="button-group"><Link className="button secondary" href={`/admin/reports/print?${new URLSearchParams(report.period)}`} target="_blank">Print / PDF</Link>{principal.permissions.includes("reports.export")?<><Link className="button secondary" href={`/api/admin/reports/export?${new URLSearchParams(report.period)}`}>CSV ↓</Link><Link className="button secondary" href={`/api/admin/reports/excel?${new URLSearchParams(report.period)}`}>Excel ↓</Link></>:null}</div>:null}</div>
  <form className="toolbar"><label>From<input type="date" name="from" required defaultValue={input.from}/></label><label>Through<input type="date" name="to" required defaultValue={input.to}/></label><button className="button">View report</button></form>
  {!report?<p className="message error">Choose valid dates spanning no more than 366 days.</p>:<>
   <div className="stats-grid"><section className="stat"><span>Room revenue</span><strong>{report.currency} {report.totals.roomRevenue}</strong><small>Nightly room charges</small></section><section className="stat"><span>Occupancy</span><strong>{report.totals.occupancy}%</strong><small>{report.totals.roomNights} of {report.totals.availableRoomNights} room-nights</small></section><section className="stat"><span>Average daily rate</span><strong>{report.currency} {report.totals.adr}</strong><small>Room revenue per occupied room-night</small></section><section className="stat"><span>Revenue per available room</span><strong>{report.currency} {report.totals.revpar}</strong><small>Room revenue per available room-night</small></section></div>
   <div className="stats-grid"><section className="stat"><span>Net collected</span><strong>{report.currency} {report.totals.net}</strong><small>{report.totals.collected} collected · {report.totals.refunded} refunded</small></section><section className="stat"><span>New reservations</span><strong>{report.totals.bookings}</strong><small>Created in selected period</small></section><section className="stat"><span>Average booking value</span><strong>{report.currency} {report.totals.averageBookingValue}</strong><small>Current totals of new reservations</small></section><section className="stat"><span>Cancellation rate</span><strong>{report.totals.cancellationRate}%</strong><small>New reservations currently cancelled</small></section></div>
   <section className="panel padded"><h2>Room revenue trend</h2><p className="muted">Nightly room charges exclude extras and taxes. This keeps operating revenue separate from payment collection timing.</p><div className="report-bars">{report.days.map(day=><div key={day.date} className="report-bar-row"><time dateTime={day.date}>{day.date}</time><span><i style={{width:`${Number(day.roomRevenue)/maxRevenue*100}%`}}/></span><strong>{day.roomRevenue}</strong></div>)}</div></section>
   <div className="split-layout"><section className="panel"><div className="panel-heading"><h2>Booking sources</h2><span>{report.totals.bookings} reservations</span></div>{report.sources.map(source=><div className="list-row" key={source.label}><span><strong>{source.label}</strong><small>{source.count} reservations</small></span><span>{report.currency} {source.amount}</span></div>)}{!report.sources.length?<div className="empty-state compact-empty"><p>No reservations in this period.</p></div>:null}</section><section className="panel"><div className="panel-heading"><h2>Reservation status</h2></div>{report.statuses.map(status=><div className="list-row" key={status.label}><span><strong>{status.label.toLowerCase().replaceAll("_"," ")}</strong><small>{status.count} reservations</small></span><span>{report.currency} {status.amount}</span></div>)}{!report.statuses.length?<div className="empty-state compact-empty"><p>No reservation activity.</p></div>:null}</section></div>
   {report.promos.length?<section className="panel"><div className="panel-heading"><h2>Promotion usage</h2><span>Discount value</span></div>{report.promos.map(promo=><div className="list-row" key={promo.label}><span><strong>{promo.label}</strong><small>{promo.count} redemptions</small></span><span>{report.currency} {promo.amount}</span></div>)}</section>:null}
   <div className="split-layout"><section className="panel"><div className="panel-heading"><h2>Tax report</h2><span>Bookings created in period</span></div>{report.taxes.map(tax=><div className="list-row" key={tax.label}><span><strong>{tax.label}</strong><small>Applied to {tax.count} reservations</small></span><span>{report.currency} {tax.amount}</span></div>)}{!report.taxes.length?<div className="empty-state compact-empty"><p>No tax charges in this period.</p></div>:null}</section><section className="panel"><div className="panel-heading"><h2>Room performance</h2><span>Stay dates in period</span></div>{report.rooms.map(room=><div className="list-row" key={room.label}><span><strong>{room.label}</strong><small>{room.roomNights} occupied room-nights</small></span><span>{report.currency} {room.amount}</span></div>)}{!report.rooms.length?<div className="empty-state compact-empty"><p>No occupied rooms in this period.</p></div>:null}</section></div>
   <section className="panel"><div className="panel-heading"><h2>Guest report</h2><span>Top 50 by reservations created</span></div>{report.guests.map(guest=><div className="list-row" key={guest.label}><span><strong>{guest.label}</strong><small>{guest.count} reservations</small></span><span>{report.currency} {guest.amount}</span></div>)}{!report.guests.length?<div className="empty-state compact-empty"><p>No guests booked in this period.</p></div>:null}</section>
   <section className="panel padded"><h2>Daily activity</h2><p className="muted">Dates use {report.timezone}. Net collected is successful payments less successful refunds recorded that day. Available rooms exclude active inventory blocked for that date.</p><div className="report-table-wrap"><table className="report-table"><thead><tr><th scope="col">Date</th><th scope="col">Room revenue</th><th scope="col">Collected</th><th scope="col">Refunded</th><th scope="col">Net</th><th scope="col">Bookings</th><th scope="col">Occupied</th><th scope="col">Available</th></tr></thead><tbody>{report.days.map(day=><tr key={day.date}><th scope="row">{day.date}</th><td>{day.roomRevenue}</td><td>{day.collected}</td><td>{day.refunded}</td><td>{day.net}</td><td>{day.bookings}</td><td>{day.roomNights}</td><td>{day.availableRooms}</td></tr>)}</tbody><tfoot><tr><th scope="row">Total ({report.currency})</th><td>{report.totals.roomRevenue}</td><td>{report.totals.collected}</td><td>{report.totals.refunded}</td><td>{report.totals.net}</td><td>{report.totals.bookings}</td><td>{report.totals.roomNights}</td><td>{report.totals.availableRoomNights}</td></tr></tfoot></table></div></section>
  </>}
 </>;
}
