"use client";
import {useState} from "react";
import type {BookingOptions} from "../domain/booking-options";
type Method={provider:string;instructions:string;bankName:string;accountName:string;accountNumber:string};
export function CheckoutForm({ratePlanId,stay,total,methods,options}:{ratePlanId:string;stay:{checkIn:string;checkOut:string;adults:number;children:number;rooms:number};total:string;options:BookingOptions;methods:Method[]}){
 const [key]=useState(()=>crypto.randomUUID()),[pending,setPending]=useState(false),[error,setError]=useState("");const [method,setMethod]=useState(methods[0]?.provider??"");const selected=methods.find(item=>item.provider===method);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({stay,ratePlanId,options,paymentMethod:method,expectedTotal:total,idempotencyKey:key,name:form.get("name"),email:form.get("email"),phone:form.get("phone"),note:form.get("note"),acceptedPolicy:form.has("acceptedPolicy")})});const data=await response.json();if(!response.ok)throw new Error(data.error);window.location.assign(data.confirmationUrl);}catch(cause){setError(cause instanceof Error?cause.message:"Reservation failed. Please try again.");setPending(false);}}
 return <form className="form" onSubmit={submit}><label>Full name<input name="name" autoComplete="name" minLength={2} maxLength={150} required/></label><div className="form-grid"><label>Email address<input name="email" type="email" autoComplete="email" required/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" minLength={5} maxLength={40} required/></label></div><label>Anything we should know?<textarea name="note" maxLength={2000}/></label><label>Payment method<select name="paymentMethod" value={method} onChange={event=>setMethod(event.target.value)}>{methods.map(item=><option key={item.provider} value={item.provider}>{item.provider.replaceAll("-"," ")}</option>)}</select></label>{selected?<div className="message"><p>{selected.instructions}</p>{selected.bankName?<p>{selected.bankName} · {selected.accountName} · {selected.accountNumber}</p>:null}</div>:null}<label className="checkbox"><input type="checkbox" name="acceptedPolicy" required/>I agree to the cancellation terms shown for this stay.</label>{error?<p className="message error" role="alert">{error}</p>:null}<button className="button" disabled={pending||!method}>{pending?"Reserving your stay…":"Confirm reservation"}</button><p className="muted">No card details are collected on this page. Follow the payment instructions for your selected method.</p></form>;
}
