import {contentDocumentSchema,contentVisible} from "../domain/content";
import {z} from "zod";import {formFieldSchema} from "../domain/forms";import {PublicForm} from "./public-form";
import Image from "next/image";import Link from "next/link";import {db} from "../server/db";import {getSettings} from "../server/cms";import {sectionVisible,type PageDocument,type PageSectionInput} from "../domain/cms";import {BookingSearch} from "./booking-search";
export async function CmsRenderer({document,propertyId}:{document:PageDocument;propertyId:string}){
 const [property,media,rooms,amenities,entries,features,newsletter]=await Promise.all([db.property.findUniqueOrThrow({where:{id:propertyId}}),db.media.findMany({where:{propertyId,state:"READY"},select:{id:true,alt:true}}),db.roomType.findMany({where:{propertyId,published:true,deletedAt:null},include:{images:{include:{media:true},orderBy:{position:"asc"},take:1}},orderBy:{featured:"desc"},take:6}),db.amenity.findMany({where:{propertyId,active:true},take:30}),db.contentEntry.findMany({where:{propertyId,status:"PUBLISHED",locale:document.locale},take:200}),getSettings(propertyId,"features"),db.customForm.findFirst({where:{propertyId,name:"Newsletter",active:true}})]);
 const alt=(id:string)=>media.find(m=>m.id===id)?.alt??"";const collection=(kind:string)=>entries.filter(e=>e.kind===kind).flatMap(e=>{const parsed=contentDocumentSchema.safeParse(e.published);return parsed.success&&contentVisible(parsed.data)?[{id:e.id,slug:e.slug,...parsed.data}]:[];});
 function render(section:PageSectionInput){const c=section.content;const intro=<div className="section-intro">{c.eyebrow&&<span className="eyebrow">{c.eyebrow}</span>}{c.heading&&<h2>{c.heading}</h2>}{c.body&&<p>{c.body}</p>}</div>;const cta=c.ctaLabel&&c.ctaUrl?<Link className="button" href={c.ctaUrl}>{c.ctaLabel} ↗</Link>:null;
  switch(section.type){
   case"hero":return <><span className="eyebrow">{c.eyebrow}</span><h1>{c.heading}</h1><p>{c.body}</p>{cta}</>;
   case"text":case"cta":return <>{intro}{cta}</>;
   case"image-text":return <div className="cms-image-text">{c.imageId&&<Image src={`/media/${c.imageId}`} alt={alt(c.imageId)} width={650} height={500}/>}<div>{intro}{cta}</div></div>;
   case"rooms":return <>{intro}<BookingSearch/><div className="room-grid">{rooms.map(room=><article className="room-card" key={room.id}><Link className="room-photo" href={`/rooms/${room.slug}`}>{room.images[0]?<Image src={`/media/${room.images[0].mediaId}`} alt={room.images[0].media.alt} fill sizes="(max-width:680px) 100vw, 50vw"/>:<div className="photo-empty">{room.name}</div>}</Link><div className="room-card-body"><h2>{room.name}</h2><p>{(room.attributes as Record<string,string>).shortDescription||room.description.slice(0,160)}</p><div className="room-card-bottom">{features.showPrices&&<span>From<strong>{property.currency} {room.basePrice.toString()}</strong><small>per night</small></span>}<Link href={`/rooms/${room.slug}`} className="text-link">Explore room ↗</Link></div></div></article>)}</div>{cta}</>;
   case"amenities":return <>{intro}<div className="amenity-list">{amenities.map(a=><span key={a.id}>✓ {a.name}</span>)}</div>{cta}</>;
   case"gallery":return <>{intro}<div className="cms-gallery">{(c.items.length?c.items:media.slice(0,9).map(m=>({title:m.alt,imageId:m.id,body:"",url:""}))).filter(item=>item.imageId).map((item,i)=><Image key={i} src={`/media/${item.imageId}`} alt={item.title||alt(item.imageId)} width={500} height={400}/>)}</div>{cta}</>;
   case"stats":return <>{intro}<div className="cms-cards">{c.items.map((item,i)=><div className="cms-stat" key={i}><strong>{item.title}</strong><p>{item.body}</p></div>)}</div></>;
   case"faq":return <>{intro}<div className="cms-faq">{(c.items.length?c.items:collection("faq").map(e=>({title:e.title,body:e.body}))).map((item,i)=><details key={i}><summary>{item.title}</summary><p>{item.body}</p></details>)}</div></>;
   case"cards":return <>{intro}<div className="cms-cards">{c.items.map((item,i)=><article className="cms-card" key={i}>{item.imageId&&<Image src={`/media/${item.imageId}`} alt={alt(item.imageId)} width={400} height={300}/>}<h3>{item.title}</h3><p>{item.body}</p>{item.url&&<Link className="text-link" href={item.url}>Learn more ↗</Link>}</article>)}</div>{cta}</>;
   case"offers":case"testimonials":return <>{intro}<div className="cms-cards">{collection(section.type).map(e=><article className="cms-card" key={e.id}>{e.imageId&&<Image src={`/media/${e.imageId}`} alt={alt(e.imageId)} width={450} height={320}/>}<h3>{e.title}</h3><p>{e.body}</p>{e.url&&<Link className="text-link" href={e.url}>{e.buttonLabel||"Explore"} ↗</Link>}</article>)}</div>{cta}</>;
   case"video":return <>{intro}{c.videoUrl&&<video className="cms-video" src={c.videoUrl} controls preload="metadata" poster={c.imageId?`/media/${c.imageId}`:undefined}><track kind="captions"/>Your browser does not support this video.</video>}{cta}</>;
   case"contact":return <>{intro}<p><Link className="button" href="/contact">Contact the hotel</Link></p>{cta}</>;
   case"newsletter":return <>{intro}{newsletter&&<PublicForm id={newsletter.id} fields={z.array(formFieldSchema).parse(newsletter.fields)} label="Subscribe"/>}</>;
  }
 }
 return <>{document.sections.filter(s=>sectionVisible(s)&&(!(s.type in features)||features[s.type]!==false)).map(section=><section key={section.id} className={`cms-section ${section.style.background} ${section.style.align} ${section.style.spacing} ${section.style.width} ${section.type==="hero"?`cms-hero ${section.content.imageId?"has-image":""}`:""}`}>{section.type==="hero"&&section.content.imageId&&<Image src={`/media/${section.content.imageId}`} alt={alt(section.content.imageId)} fill priority sizes="100vw"/>}<div className="cms-inner">{render(section)}</div></section>)}</>;
}
