"use client";
import {useEffect,useRef,useState} from "react";import Image from "next/image";
type Config=Record<string,string|number|boolean>;
export function GuestPreferences({cookies,popup,tracking}:{cookies:Config;popup:Config;tracking:Config}){
 const [consent,setConsent]=useState<string|null>("loading"),[showPopup,setShowPopup]=useState(false);const dialog=useRef<HTMLDivElement>(null);
 useEffect(()=>{const value=localStorage.getItem("hotel-cookie-preference");queueMicrotask(()=>setConsent(value));},[]);
 useEffect(()=>{if(consent!=="optional"||!tracking.enabled||!tracking.googleAnalyticsId)return;const id=String(tracking.googleAnalyticsId);const analytics=window as unknown as {dataLayer:unknown[];gtag:(...args:unknown[])=>void};analytics.dataLayer=analytics.dataLayer??[];analytics.gtag=(...args)=>analytics.dataLayer.push(args);analytics.gtag("js",new Date());analytics.gtag("config",id,{anonymize_ip:true});const script=document.createElement("script");script.async=true;script.src=`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(id)}`;document.head.appendChild(script);return()=>script.remove();},[consent,tracking]);
 useEffect(()=>{if(!popup.enabled)return;const now=Date.now(),start=popup.startsAt?Date.parse(String(popup.startsAt)):0,end=popup.endsAt?Date.parse(String(popup.endsAt)):Infinity;if(now<start||now>=end)return;const last=Number(localStorage.getItem("hotel-popup-dismissed")??0);if(now-last<Number(popup.frequencyDays)*86400000)return;const timer=setTimeout(()=>setShowPopup(true),Number(popup.delaySeconds)*1000);return()=>clearTimeout(timer);},[popup]);
 useEffect(()=>{if(showPopup)dialog.current?.querySelector<HTMLButtonElement>("button")?.focus();},[showPopup]);
 function choose(value:string){const previous=localStorage.getItem("hotel-cookie-preference");localStorage.setItem("hotel-cookie-preference",value);if(previous==="optional"&&value==="essential"){window.location.reload();return;}setConsent(value);}
 function close(){setShowPopup(false);localStorage.setItem("hotel-popup-dismissed",String(Date.now()));}
 return <><button className="consent-link" onClick={()=>setConsent(null)}>Cookie preferences</button>{cookies.enabled&&consent===null&&<section className="cookie-banner" role="region" aria-label="Cookie preferences"><p>{String(cookies.message)} <a href={String(cookies.policyUrl)}>Privacy policy</a></p><div className="button-group"><button className="button secondary" onClick={()=>choose("essential")}>{String(cookies.rejectLabel)}</button><button className="button" onClick={()=>choose("optional")}>{String(cookies.acceptLabel)}</button></div></section>}{showPopup&&<div className="popup-backdrop" onClick={close}><div ref={dialog} className="popup-card" role="dialog" aria-modal="true" aria-labelledby="popup-heading" onClick={event=>event.stopPropagation()} onKeyDown={event=>{if(event.key==="Escape")close();if(event.key==="Tab"){const nodes=dialog.current?.querySelectorAll<HTMLElement>("button,a[href],input");if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}}><button aria-label="Close promotion" onClick={close}>×</button>{popup.imageId&&<Image src={`/media/${popup.imageId}`} alt="" width={540} height={300}/>}<h2 id="popup-heading">{String(popup.title)}</h2><p>{String(popup.body)}</p>{popup.buttonUrl&&<a className="button" href={String(popup.buttonUrl)}>{String(popup.buttonLabel)}</a>}</div></div>}</>;
}
