import {NewsletterSignup} from "./newsletter-signup";
import Link from "next/link";import Image from "next/image";import type {CSSProperties} from "react";import {db} from "../server/db";import {getSettings} from "../server/cms";import {GuestPreferences} from "./guest-preferences";import {Announcement} from "./announcement";
const fonts:Record<string,string>={"Libre Caslon Display":"'Libre Caslon Display', Georgia, serif","DM Sans":"'DM Sans', Arial, sans-serif",Georgia:"Georgia, serif",Arial:"Arial, sans-serif",Verdana:"Verdana, sans-serif"};
type Item={id:string;parentId:string|null;label:string;url:string;newTab:boolean;position:number};
function MenuLinks({items,parentId=null,depth=0}:{items:Item[];parentId?:string|null;depth?:number}){if(depth>3)return null;return <>{items.filter(i=>i.parentId===parentId).map(item=><div className="nav-group" key={item.id}><Link href={item.url||"#"} target={item.newTab?"_blank":undefined} rel={item.newTab?"noopener noreferrer":undefined}>{item.label}</Link>{items.some(i=>i.parentId===item.id)&&<div className="nav-dropdown"><MenuLinks items={items} parentId={item.id} depth={depth+1}/></div>}</div>)}</>;}
export async function HotelShell({children,preview=false}:{children:React.ReactNode;preview?:boolean}){
 const property=await db.property.findFirstOrThrow();const namespaces=["theme","header","footer","cookies","popup","tracking","announcement","maintenance","features"];
 const [config,menus,values]=await Promise.all([db.configuration.findUnique({where:{propertyId_namespace:{propertyId:property.id,namespace:"hotel"}}}),db.menu.findMany({where:{propertyId:property.id},include:{items:{where:{visible:true},orderBy:{position:"asc"}}}}),Promise.all(namespaces.map(n=>getSettings(property.id,n,preview)))]);
 const [theme,header,footer,cookies,popup,tracking,announcement,maintenance,features]=values;const hotel=(config?.published??{}) as Record<string,string>;
 const style={"--ink":theme.text,"--muted":theme.muted,"--accent":theme.primary,"--mist":theme.secondaryBackground,"--paper":theme.background,"--radius":`${theme.radius}px`,"--body":fonts[String(theme.bodyFont)],"--heading":fonts[String(theme.headingFont)],"--content-width":`${theme.contentWidth}px`,"--section-spacing":`${theme.sectionSpacing}px`,"--public-heading-color":theme.heading,"--public-heading-size":`${theme.headingSize}px`,"--button-bg":theme.button,"--button-text":theme.buttonText,"--public-link":theme.link,"--nav-font":fonts[String(theme.navigationFont)],"--button-font":fonts[String(theme.buttonFont)],background:String(theme.background),color:String(theme.text),fontFamily:fonts[String(theme.bodyFont)],fontSize:Number(theme.bodySize),lineHeight:Number(theme.lineHeight)/100} as CSSProperties;
 // This async server component evaluates scheduled content once per request.
 // eslint-disable-next-line react-hooks/purity
 const now=Date.now();
 return <div className="hotel-site" style={style}>{preview&&<div className="preview-bar">Authenticated preview · These changes are not necessarily published.</div>}<Announcement config={announcement} now={now}/><header className="hotel-header" style={{background:header.transparent?"transparent":String(header.background),color:String(header.text),minHeight:Number(header.height),position:header.sticky?"sticky":"relative",top:0,zIndex:35}}><Link className="hotel-brand" href="/">{theme.logoId?<Image src={`/media/${theme.logoId}`} alt={property.name} width={Number(header.logoWidth)} height={60} style={{objectFit:"contain",height:"auto"}}/>:property.name}{theme.tagline&&<small className="hotel-tagline">{String(theme.tagline)}</small>}</Link><nav aria-label="Main navigation"><MenuLinks items={menus.find(m=>m.name==="header")?.items??[]}/>{header.showPhone&&hotel.phone&&<a href={`tel:${hotel.phone}`}>{hotel.phone}</a>}{header.showEmail&&hotel.email&&<a href={`mailto:${hotel.email}`}>{hotel.email}</a>}</nav>{header.buttonLabel&&<Link className="button secondary" href={String(header.buttonUrl)||"/rooms"}>{String(header.buttonLabel)} ↗</Link>}</header>{maintenance.enabled&&!preview?<main id="main" className="coming-soon"><h1>{String(maintenance.title)}</h1><p>{String(maintenance.message)}</p><p>{String(maintenance.reopening)}</p>{maintenance.imageId&&<Image src={`/media/${maintenance.imageId}`} alt="" width={500} height={300}/>}<p>{hotel.phone}</p>{hotel.email&&<a className="text-link" href={`mailto:${hotel.email}`}>{hotel.email}</a>}</main>:children}<footer className="hotel-footer" style={{background:String(footer.background),color:String(footer.text)}}><div><Link className="hotel-brand" href="/">{property.name}</Link><p>{String(footer.description)||hotel.description}</p>{footer.newsletter&&features.newsletter&&<NewsletterSignup propertyId={property.id}/>}{["instagram","facebook","youtube"].filter(key=>footer[key]).map(key=><a key={key} href={String(footer[key])} target="_blank" rel="noopener noreferrer">{key}</a>)}</div><div><h3>{String(footer.contactHeading)}</h3><p>{hotel.address}</p>{hotel.email&&<a href={`mailto:${hotel.email}`}>{hotel.email}</a>}{hotel.phone&&<a href={`tel:${hotel.phone}`}>{hotel.phone}</a>}<nav aria-label="Footer navigation"><MenuLinks items={menus.find(m=>m.name==="footer")?.items??[]}/></nav></div><div><h3>{String(footer.arrivalHeading)}</h3><p>Check-in {hotel.checkIn??"14:00"}</p><p>Check-out {hotel.checkOut??"11:00"}</p><Link href="/admin">Property team ↗</Link><p>{String(footer.copyright)}</p>{!preview&&<GuestPreferences cookies={cookies} popup={popup} tracking={tracking}/>}</div></footer></div>;
}
