"use client";
import {useState} from "react";

type LinkType="internal"|"external"|"page";
type PageOption={id:string;title:string;slug:string;status:string};
type Item={id:string;label:string;url:string;linkType:LinkType;pageId:string|null;externalUrl:string|null;parentId:string|null;visible:boolean;newTab:boolean};

export function NavigationEditor({name,initial,pages}:{name:string;initial:Item[];pages:PageOption[]}){
 const [items,setItems]=useState(initial),[pending,setPending]=useState(false),[message,setMessage]=useState("");
 const update=(id:string,data:Partial<Item>)=>setItems(current=>current.map(item=>item.id===id?{...item,...data}:item));
 const save=async()=>{setPending(true);setMessage("");const payload={name,items:items.map((item,order)=>({...item,label:item.label.trim(),url:item.linkType==="external"?(item.externalUrl??""):item.url.trim(),externalUrl:item.linkType==="external"?(item.externalUrl??""):null,pageId:item.linkType==="page"?item.pageId:null,parentId:item.parentId||null,order}))};try{const response=await fetch("/api/admin/navigation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error??"Navigation could not be saved.");setMessage("Navigation saved.");}catch(error){setMessage(error instanceof Error?error.message:"Navigation could not be saved.");}finally{setPending(false);}};
 return <div className="form">{items.map((item,index)=><fieldset key={item.id}><legend>Link {index+1}</legend><div className="form-grid"><label>Label<input value={item.label} onChange={event=>update(item.id,{label:event.target.value})}/></label><label>Link type<select value={item.linkType} onChange={event=>update(item.id,{linkType:event.target.value as LinkType})}><option value="internal">Internal path</option><option value="external">External URL</option><option value="page">CMS page</option></select></label>{item.linkType==="page"?<label>Target page<select value={item.pageId??""} onChange={event=>update(item.id,{pageId:event.target.value||null})}><option value="">Choose a page</option>{pages.map(page=><option key={page.id} value={page.id}>{page.title} ({page.status.toLowerCase()})</option>)}</select></label>:<label>{item.linkType==="external"?"External URL":"Link URL"}<input value={item.linkType==="external"?(item.externalUrl??""):item.url} onChange={event=>item.linkType==="external"?update(item.id,{externalUrl:event.target.value}):update(item.id,{url:event.target.value})}/></label>}<label>Parent item<select value={item.parentId??""} onChange={event=>update(item.id,{parentId:event.target.value||null})}><option value="">Top level</option>{items.filter(other=>other.id!==item.id).map(other=><option key={other.id} value={other.id}>{other.label||"Untitled link"}</option>)}</select></label><div className="check-grid"><label className="checkbox"><input type="checkbox" checked={item.visible} onChange={event=>update(item.id,{visible:event.target.checked})}/>Visible</label><label className="checkbox"><input type="checkbox" checked={item.newTab} onChange={event=>update(item.id,{newTab:event.target.checked})}/>Open in a new tab</label></div></div><div className="button-group"><button type="button" className="plain-button" disabled={index===0} onClick={()=>{const next=[...items];[next[index-1],next[index]]=[next[index],next[index-1]];setItems(next);}}>Move up</button><button type="button" className="plain-button" disabled={index===items.length-1} onClick={()=>{const next=[...items];[next[index],next[index+1]]=[next[index+1],next[index]];setItems(next);}}>Move down</button><button type="button" className="plain-button" onClick={()=>{if(window.confirm("Remove this navigation link?"))setItems(items.filter(other=>other.id!==item.id).map(other=>other.parentId===item.id?{...other,parentId:null}:other));}}>Remove</button></div></fieldset>)}<button type="button" className="button secondary" onClick={()=>setItems([...items,{id:crypto.randomUUID(),label:"",url:"",linkType:"internal",pageId:null,externalUrl:null,parentId:null,visible:true,newTab:false}])}>+ Add link</button>{message&&<p className="message" role="status">{message}</p>}<button type="button" className="button" disabled={pending} onClick={save}>{pending?"Saving…":"Save navigation"}</button></div>;
}
