import { ActionForm } from "./action-form";
import { saveRoom } from "../server/room-actions";
type Room = { id: string; name: string; slug: string; description: string; basePrice: string; maxAdults: number; maxChildren: number; maxGuests: number; published: boolean; featured: boolean; attributes: Record<string, unknown>; amenityIds: string[]; mediaId: string };
export function RoomEditor({ room, amenities, media, currency }: { room?: Room; amenities: { id: string; name: string }[]; media: { id: string; alt: string }[]; currency: string }) {
  const attr = room?.attributes ?? {};
  return <ActionForm action={saveRoom} label={room ? "Save room" : "Create room"}><input type="hidden" name="id" value={room?.id ?? ""} />
    <div className="form-grid"><label>Room name<input name="name" defaultValue={room?.name} required /></label><label>Page address<input name="slug" defaultValue={room?.slug} placeholder="deluxe-king" pattern="[a-z0-9]+(-[a-z0-9]+)*" required /></label></div>
    <label>Short description<input name="shortDescription" defaultValue={String(attr.shortDescription ?? "")} maxLength={300} /></label><label>Full description<textarea name="description" defaultValue={room?.description} required minLength={10} /></label>
    <div className="form-grid"><label>Base nightly price ({currency})<input type="number" name="basePrice" min="0" step="0.01" defaultValue={room?.basePrice ?? "0"} required /></label><label>Featured photo<select name="mediaId" defaultValue={room?.mediaId}><option value="">No photo selected</option>{media.map(m => <option value={m.id} key={m.id}>{m.alt}</option>)}</select></label></div>
    <div className="form-grid">{[["maxAdults", "Maximum adults", room?.maxAdults ?? 2], ["maxChildren", "Maximum children", room?.maxChildren ?? 0], ["maxGuests", "Total guest capacity", room?.maxGuests ?? 2], ["size", "Room size (m²)", attr.size ?? 0], ["beds", "Number of beds", attr.beds ?? 1], ["bathrooms", "Bathrooms", attr.bathrooms ?? 1]].map(([name,label,value]) => <label key={String(name)}>{String(label)}<input type="number" name={String(name)} min="0" defaultValue={String(value)} required /></label>)}</div>
    <div className="form-grid">{[["bedType", "Bed type"], ["view", "View"], ["floor", "Floor"], ["videoUrl", "Video URL"]].map(([name,label]) => <label key={name}>{label}<input name={name} defaultValue={String(attr[name] ?? "")} /></label>)}</div>
    <fieldset><legend>Room features</legend><div className="check-grid">{[["published", "Visible on website", room?.published], ["featured", "Featured room", room?.featured], ["smoking", "Smoking allowed", attr.smoking], ["accessible", "Accessible room", attr.accessible], ["breakfast", "Breakfast included", attr.breakfast]].map(([name,label,checked]) => <label className="checkbox" key={String(name)}><input type="checkbox" name={String(name)} defaultChecked={Boolean(checked)} />{String(label)}</label>)}</div></fieldset>
    <fieldset><legend>Amenities</legend><div className="check-grid">{amenities.length ? amenities.map(a => <label className="checkbox" key={a.id}><input type="checkbox" name="amenities" value={a.id} defaultChecked={room?.amenityIds.includes(a.id)} />{a.name}</label>) : <p className="muted">Create amenities in the Amenities screen to assign them here.</p>}</div></fieldset>
  </ActionForm>;
}
