import Link from "next/link";
import {db} from "../../../server/db";
import {requireUser} from "../../../server/auth";
import {digest} from "../../../server/crypto";
import {notificationKeys,notificationLabels,notificationVariables,defaultNotificationTemplates} from "../../../domain/notifications";
import {saveNotificationTemplate,retryNotification} from "../../../server/notification-actions";
import {ActionForm} from "../../../components/action-form";

export default async function Notifications({searchParams}:{searchParams:Promise<{key?:string;locale?:string}>}){
 const {property}=await requireUser("settings.manage");const query=await searchParams;
 const key=notificationKeys.find(key=>key===query.key)??notificationKeys[0];const locale=["en","bn","ar","hi"].find(locale=>locale===query.locale)??property.locale;
 const [template,events]=await Promise.all([db.emailTemplate.findUnique({where:{propertyId_key_locale:{propertyId:property.id,key,locale}}}),db.outboxEvent.findMany({where:{propertyId:property.id},orderBy:{availableAt:"desc"},take:50})]);
 const fingerprint=template?digest(JSON.stringify({subject:template.subject,content:template.content,active:template.active})):"new";
 const configured=Boolean(process.env.EMAIL_API_KEY&&process.env.EMAIL_FROM);
 return <><div className="page-heading"><div><span className="eyebrow">GUEST COMMUNICATION</span><h1>Emails & delivery.</h1><p className="muted">Edit reservation emails and review the latest 50 delivery jobs.</p></div><span className={`badge ${configured?"green":""}`}>{configured?"Email provider configured":"Email provider not configured"}</span></div>{!configured&&<p className="message">Email delivery is paused. Configure a verified sender and start the delivery worker to send queued messages.</p>}<div className="split-layout"><section className="panel padded"><h2>Email templates</h2><nav className="content-tabs" aria-label="Email templates">{notificationKeys.map(value=><Link key={value} href={`?key=${value}&locale=${locale}`} aria-current={key===value?"page":undefined}>{notificationLabels[value]}</Link>)}</nav><nav className="content-tabs" aria-label="Template language">{["en","bn","ar","hi"].map(value=><Link key={value} href={`?key=${key}&locale=${value}`} aria-current={locale===value?"page":undefined}>{value}</Link>)}</nav><ActionForm key={`${key}:${locale}:${fingerprint}`} action={saveNotificationTemplate} label="Save email template"><input type="hidden" name="key" value={key}/><input type="hidden" name="locale" value={locale}/><input type="hidden" name="fingerprint" value={fingerprint}/><label>Subject<input name="subject" required maxLength={200} defaultValue={template?.subject??defaultNotificationTemplates[key].subject}/></label><label>Message<textarea name="body" required rows={12} maxLength={20000} defaultValue={(template?.content as {body?:string}|null)?.body??defaultNotificationTemplates[key].body}/></label><label className="checkbox"><input type="checkbox" name="active" defaultChecked={template?.active??true}/>Send this email</label><p className="muted">Available placeholders: {notificationVariables.map(variable=>`{{${variable}}}`).join(", ")}</p><p className="muted">Changes apply to messages when the worker processes them. Disabling a template skips its queued messages.</p></ActionForm></section><section className="panel"><div className="panel-heading"><h2>Delivery queue</h2></div>{events.map(event=><div className="list-row" key={event.id}><span><strong>{notificationLabels[event.kind as typeof notificationKeys[number]]??event.kind}</strong><small>{event.lastErrorCode==="TEMPLATE_DISABLED"?"Skipped · template disabled":event.deliveredAt?"Delivered":event.attempts>=8?"Failed · retry needed":event.lastErrorCode?"Waiting to retry":"Queued"} · {event.attempts} attempts</small><small>{event.availableAt.toLocaleString("en-GB",{timeZone:property.timezone})}</small></span>{!event.deliveredAt&&event.lastErrorCode&&<ActionForm action={retryNotification} label="Retry"><input type="hidden" name="id" value={event.id}/></ActionForm>}</div>)}{!events.length&&<div className="empty-state"><h3>No delivery jobs yet.</h3><p>Booking confirmations and payment receipts appear here when created.</p></div>}</section></div></>;
}
