import Image from "next/image";import Link from "next/link";import {notFound} from "next/navigation";
import {db} from "../../../server/db";import {searchAvailability} from "../../../server/availability";
import {HotelShell} from "../../../components/hotel-shell";import {BookingSearch} from "../../../components/booking-search";
export const dynamic="force-dynamic";
export default async function RoomDetails({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {slug}=await params,query=await searchParams;const property=await db.property.findFirstOrThrow();const room=await db.roomType.findFirst({where:{propertyId:property.id,slug,published:true,deletedAt:null},include:{images:{include:{media:true},orderBy:{position:"asc"}},amenities:{include:{amenity:true}}}});if(!room)notFound();const attr=room.attributes as Record<string,string|number|boolean>;
 let rates:Awaited<ReturnType<typeof searchAvailability>>[number]["rates"]=[];let error="";if(query.checkIn&&query.checkOut){try{rates=(await searchAvailability(property.id,{checkIn:query.checkIn,checkOut:query.checkOut,adults:Number(query.adults??2),children:Number(query.children??0),rooms:Number(query.rooms??1)})).find(r=>r.room.id===room.id)?.rates??[];if(!rates.length)error="This room is unavailable for these dates. Try another stay.";}catch{error="Please check your dates and guest counts.";}}
 const values=new URLSearchParams(Object.entries(query).filter((e):e is[string,string]=>typeof e[1]==="string"));
 return <HotelShell><main id="main"><div className="public-container"><Link className="back-link" href="/rooms">← All rooms</Link><div className="room-detail-heading"><div><span className="eyebrow">YOUR PRIVATE RETREAT</span><h1>{room.name}</h1></div><p>Up to {room.maxGuests} guests · {String(attr.size??0)} m² · {String(attr.bedType??"")}</p></div>{room.images[0]&&<div className="detail-photo"><Image src={`/media/${room.images[0].mediaId}`} alt={room.images[0].media.alt} fill priority sizes="100vw"/></div>}<div className="room-detail-columns"><section><h2>Make yourself comfortable.</h2><p className="room-description">{room.description}</p><dl className="room-facts"><div><dt>Beds</dt><dd>{String(attr.beds??1)} {String(attr.bedType??"")}</dd></div><div><dt>Bathrooms</dt><dd>{String(attr.bathrooms??0)}</dd></div>{attr.view&&<div><dt>View</dt><dd>{String(attr.view)}</dd></div>}{attr.floor&&<div><dt>Floor</dt><dd>{String(attr.floor)}</dd></div>}<div><dt>Smoking</dt><dd>{attr.smoking?"Allowed":"Non-smoking"}</dd></div><div><dt>Breakfast</dt><dd>{attr.breakfast?"Included":"See your selected rate"}</dd></div>{attr.accessible&&<div><dt>Accessibility</dt><dd>Accessible room. Contact the hotel for specific requirements.</dd></div>}</dl>{attr.videoUrl&&<a className="text-link" href={String(attr.videoUrl)} target="_blank" rel="noopener noreferrer">View room video</a>}<h3>Thoughtful comforts</h3><div className="amenity-list">{room.amenities.filter(a=>a.amenity.active).map(a=><span key={a.amenityId}>✓ {a.amenity.name}</span>)}</div></section><aside className="panel padded"><h2>Your stay</h2><p className="muted">Select dates to see rates and availability.</p><BookingSearch values={query}/></aside></div>{error&&<p className="message error">{error}</p>}{rates.length>0&&<section className="rate-selection"><h2>Choose your rate</h2>{rates.map(rate=><div className="rate-choice" key={rate.id}><div><h3>{rate.name}</h3><p className="muted">{rate.policy.name} · {rate.quote.nights} nights</p></div><strong>{property.currency} {rate.quote.total}</strong><Link className="button" href={`/checkout?${values}&ratePlanId=${rate.id}`}>Reserve this stay ↗</Link></div>)}</section>}</div></main></HotelShell>;
}
