import Link from "next/link";
import { db } from "../../../server/db";
import { requireUser } from "../../../server/auth";
export default async function Rooms({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
  const { property, principal } = await requireUser("rooms.view");
  const { q = "", page: pageInput } = await searchParams;
  const page = Math.max(1, Number(pageInput) || 1);
  const where = { propertyId: property.id, deletedAt: null, name: { contains: q.slice(0,100), mode: "insensitive" as const } };
  const [rooms, count] = await Promise.all([db.roomType.findMany({ where, include: { _count: { select: { units: true } } }, orderBy: { name: "asc" }, take: 20, skip: (page-1)*20 }), db.roomType.count({ where })]);
  return <><div className="page-heading"><div><span className="eyebrow">ACCOMMODATION</span><h1>Room to unwind.</h1><p className="muted">Manage the spaces your guests will call their own.</p></div>{principal.permissions.includes("rooms.edit") && <Link className="button" href="/admin/rooms/new">+ Add room type</Link>}</div><section className="panel"><div className="panel-heading"><h2>Room types <span className="count">{count}</span></h2><form className="search-form"><input name="q" defaultValue={q} placeholder="Search rooms…" aria-label="Search rooms" /><button>Search</button></form></div>{rooms.length ? <div className="table-scroll"><table><thead><tr><th>Room</th><th>Capacity</th><th>Base rate</th><th>Units</th><th>Website</th><th /></tr></thead><tbody>{rooms.map(r => <tr key={r.id}><td><strong>{r.name}</strong><small>/{r.slug}</small></td><td>{r.maxGuests} guests</td><td>{new Intl.NumberFormat("en",{style:"currency",currency:property.currency}).format(Number(r.basePrice))}</td><td>{r._count.units}</td><td><span className={`badge ${r.published ? "green" : ""}`}>{r.published ? "Published" : "Draft"}</span></td><td>{principal.permissions.includes("rooms.edit") && <Link className="row-link" href={`/admin/rooms/${r.id}`}>Edit ↗</Link>}</td></tr>)}</tbody></table></div> : <div className="empty-state"><h3>{q ? "No matching rooms." : "A place for your first room."}</h3><p>{q ? "Try another room name." : "Create a room type, then add its physical room numbers."}</p></div>}<div className="pagination"><span>{count} room types · Page {page}</span>{page>1 && <Link href={`?page=${page-1}&q=${encodeURIComponent(q)}`}>Previous</Link>}{page*20<count && <Link href={`?page=${page+1}&q=${encodeURIComponent(q)}`}>Next</Link>}</div></section></>;
}
