import {getSettings} from "../../server/cms";
import Link from "next/link";import Image from "next/image";
import {db} from "../../server/db";import {searchAvailability} from "../../server/availability";
import {HotelShell} from "../../components/hotel-shell";import {BookingSearch} from "../../components/booking-search";
export const dynamic="force-dynamic";
export default async function RoomsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const query=await searchParams;const property=await db.property.findFirst();if(!property)return <main id="main" className="coming-soon"><h1>Welcome.</h1><Link href="/setup">Set up your hotel</Link></main>;
 const features=await getSettings(property.id,"features");
 let error="";let available:Awaited<ReturnType<typeof searchAvailability>>|null=null;
 if(query.checkIn&&query.checkOut){try{available=await searchAvailability(property.id,{checkIn:query.checkIn,checkOut:query.checkOut,adults:Number(query.adults??2),children:Number(query.children??0),rooms:Number(query.rooms??1)});}catch{error="Please check your dates and guest counts. This stay may fall outside our booking rules.";}}
 const rooms=available?available.map(r=>r.room):await db.roomType.findMany({where:{propertyId:property.id,published:true,deletedAt:null},include:{images:{include:{media:true},orderBy:{position:"asc"},take:1}},orderBy:{name:"asc"}});
 const params=new URLSearchParams(Object.entries(query).filter((entry):entry is [string,string]=>typeof entry[1]==="string"));
 return <HotelShell><main id="main"><div className="hotel-page-heading"><span className="eyebrow">SPACE TO SLOW DOWN</span><h1>A stay of your own.</h1><p>Find your room, settle in, and make the most of your time here.</p></div><div className="public-container"><BookingSearch values={query}/>{error&&<p className="message error" role="alert">{error}</p>}<div className="room-grid">{rooms.map(room=>{const result=available?.find(r=>r.room.id===room.id);const price=result?.rates[0]?.quote.total;return <article className="room-card" key={room.id}><Link href={`/rooms/${room.slug}?${params}`} className="room-photo">{room.images[0]?<Image src={`/media/${room.images[0].mediaId}`} alt={room.images[0].media.alt} fill sizes="(max-width:700px) 100vw, 50vw"/>:<div className="photo-empty">{room.name}</div>}</Link><div className="room-card-body"><span className="eyebrow">UP TO {room.maxGuests} GUESTS</span><h2><Link href={`/rooms/${room.slug}?${params}`}>{room.name}</Link></h2><p>{(room.attributes as Record<string,string>).shortDescription||room.description.slice(0,160)}</p><div className="room-card-bottom">{features.showPrices&&<span>{price?"Stay total":"From"}<strong>{new Intl.NumberFormat("en",{style:"currency",currency:property.currency}).format(Number(price??room.basePrice))}</strong><small>{price?`${query.checkIn} — ${query.checkOut}`:"per night"}</small></span>}{features.showInventory&&result&&<small>{result.available} available</small>}<Link className="text-link" href={`/rooms/${room.slug}?${params}`}>Explore room ↗</Link></div></div></article>})}</div>{!rooms.length&&<div className="empty-state"><h2>{available?"A different date, perhaps?":"Our rooms are being prepared."}</h2><p>{available?"No rooms are available for this stay. Try another date or guest count.":"Please contact the property for room information."}</p></div>}</div></main></HotelShell>;
}
